### ISSUE TITLE
the results of Dance

### ISSUE THREAD

**Issue by PanXiongAdam** [lkevinzc/dance#22]
Hi, so sorry to bother you. I run the code of dance, but it have the error results of the method.  I think the ml_nms module which causes the case. However, I don't change the code. Have you ever had this kind of situation?

![image](https://user-images.githubusercontent.com/32896464/172980500-13f5bbbd-b42b-4c86-8a97-6b77b15e233e.png)

**Comment by lkevinzc** [comment]
Hi @PanXiongAdam , thanks for the issue. Which model weight did you use? Perhaps you can check #17, where I think the visualizations are correct.

**Comment by PanXiongAdam** [comment]
Thanks for your reply. I use the 'configs/Dance_R_50_3x.yaml' and the model weight is r50_3x_model_final.pth. My colleague said the environment maybe cause the problem. So, Is it convenient for you to provide the docker?

**Comment by lkevinzc** [comment]
Sorry I did not use docker for this project. I simply used `conda` environment, and I guess the version of dependencies might cause an issue. Please check here https://github.com/lkevinzc/dance#get-started and maybe try to install the corresponding version? Besides, when you run the evaluation, how about the AP scores? If the AP scores look correct but visualizations don't, I think the problem is inside the visualization functions.

**Comment by PanXiongAdam** [comment]
thanks, I will check it again.

**Comment by PanXiongAdam** [comment]
hello, I check https://github.com/lkevinzc/dance/issues/17. It is the similar result with https://github.com/lkevinzc/dance/issues/17, but the other image is the error results, so can you offer the visual method? thank you very much.
