### ISSUE TITLE
about activation function

### ISSUE THREAD

**Issue by feizhaixiaomimei** [lkevinzc/dance#3]
Thank you for your great work,I have a question:
In the paper,you add a "tanh" activation function to the snake prediction before multiplying it by the object scale.Why do you choose the activation function?

**Comment by lkevinzc** [comment]
Hi @feizhaixiaomimei thanks for your interest.
It is because we hope to match the scales. Since the input coordinates are normalised to be [0, 1], we want the output to be a _multiplicative factor_ on the width/height, so that it does not need to care about the absolute object scales. After `tanh`, the bounded range [-1, 1] is suitable for such _multiplicative factor_. Here we assumed the offsets should not be larger than h/w.
